name: Java CI

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Change wrapper permissions
                run: chmod +x ./gradlew

            -   name: Gradle Build
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: shadowJar --scan
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   id: commit
                uses: pr-mpt/actions-commit-hash@v1

            -   uses: actions/upload-artifact@v3
                with:
                    name: MikChanNoMaintenanceMode-dev-${{ steps.commit.outputs.short }}.zip
                    path: |
                        build/libs/
                        LICENSE.txt
